name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-release:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libgexiv2-dev pkg-config

      - name: Build binary
        run: cargo build --release --verbose

      - name: Strip binary
        run: strip target/release/medars

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/medars
